from distutils.core import setup
setup(
  name = 'RepetitiveTimer',
  packages = ['RepetitiveTimer'],
  version = '0.1',
  license='MIT',
  description = 'A wrapper around builtin threading module to automate repetitive timing.',
  author = 'Ömer Feyyaz Selçuk',
  author_email = 'omrfyyz@gmail.com',
  url = 'https://github.com/divisia/RepetitiveTimer',
  download_url = 'https://github.com/divisia/RepetitiveTimer/archive/v_01.tar.gz',
  keywords = ['timer', 'repetitive'],
  install_requires=[],
  classifiers=[
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
  ],
)